JWT:
  ACCESS: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  REFRESH: I1NiJ9eyJpZCI6IiIsImlhdCI6MTY3NzU1ODAwMSwiZXhwIjoxN
  
mybatis:
  mapper-locations: sqlmapper/*.xml
  type-aliases-package: com.example.demo.mapper
  
server:
  port: 8090
  
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://121.167.52.69:29032/winectweb?serverTimezone=UTC&characterEncoding=UTF-8
    password: 'winect'
    username: winect
    
  data:
    mongodb:
      database: winect
      authentication-database: winect
      username: winect
      password: winect
      host: 121.167.52.69
      port: 29017
      
#Gateway
gateway:
  symbol: gw
  protocol: http
  url: 121.167.52.69:29001
  admin-path: admin
  api_def_host: 121.167.52.69:29000
  path:
    metrics: metrics
    service: services
    route: routes
    consumer: consumers
    filter: filters
    domain: domains
    load_balancing: loadBalancingGroups
    certification: certs
    component: components
    
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    

    
springdoc:
  packages-to-scan: com.example.demo
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui-bandee.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true